name: test
on: push
jobs:
  test:
    runs-on: ubuntu-22.04
    container: ryuichiueda/ubuntu22.04-ros2:latest
    steps:
      - uses: actions/checkout@v2
      - name: Fix ROS 2 APT GPG key issue (full reset)
        run: |
          apt-get clean
          rm -f /etc/apt/sources.list.d/ros2-latest.list
          rm -f /usr/share/keyrings/ros-archive-keyring.gpg
          curl -sSL https://raw.githubusercontent.com/ros/rosdistro/master/ros.key \
            -o /usr/share/keyrings/ros-archive-keyring.gpg
          echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/ros-archive-keyring.gpg] \
            http://packages.ros.org/ros2/ubuntu $(lsb_release -sc) main" \
            > /etc/apt/sources.list.d/ros2-latest.list
          apt-get update
      - name: Install python3 in container
        run: |
          apt-get install -y python3 python3-pip python3-venv
      - name: build and test
        run: |
           rsync -av ./ /root/ros2_ws/src/mypkg/
           cd /root/ros2_ws
           bash -xv ./src/mypkg/test/test.bash /root

